language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - pyrus install http://phptal.org/latest.tar.gz
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - phpcs --standard=PSR2 src
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - benjamin.geissler@gmail.com
